FROM golang:alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /chat-service microservices/chatServer/main.go

FROM scratch

COPY --from=builder /chat-service /chat-service

EXPOSE 8081
EXPOSE 8082
EXPOSE 8083

ENTRYPOINT ["/chat-service"]
