// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delivery/grpc/calendar/proto/calendar.proto

package calendar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type EventData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	ClassID              int32    `protobuf:"varint,6,opt,name=classID,proto3" json:"classID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventData) Reset()         { *m = EventData{} }
func (m *EventData) String() string { return proto.CompactTextString(m) }
func (*EventData) ProtoMessage()    {}
func (*EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{1}
}

func (m *EventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventData.Unmarshal(m, b)
}
func (m *EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventData.Marshal(b, m, deterministic)
}
func (m *EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventData.Merge(m, src)
}
func (m *EventData) XXX_Size() int {
	return xxx_messageInfo_EventData.Size(m)
}
func (m *EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_EventData proto.InternalMessageInfo

func (m *EventData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EventData) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *EventData) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *EventData) GetClassID() int32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

type GetEventsRequestCalendar struct {
	TeacherID            int32    `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequestCalendar) Reset()         { *m = GetEventsRequestCalendar{} }
func (m *GetEventsRequestCalendar) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequestCalendar) ProtoMessage()    {}
func (*GetEventsRequestCalendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{2}
}

func (m *GetEventsRequestCalendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequestCalendar.Unmarshal(m, b)
}
func (m *GetEventsRequestCalendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequestCalendar.Marshal(b, m, deterministic)
}
func (m *GetEventsRequestCalendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequestCalendar.Merge(m, src)
}
func (m *GetEventsRequestCalendar) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequestCalendar.Size(m)
}
func (m *GetEventsRequestCalendar) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequestCalendar.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequestCalendar proto.InternalMessageInfo

func (m *GetEventsRequestCalendar) GetTeacherID() int32 {
	if m != nil {
		return m.TeacherID
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*EventData `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{3}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*EventData {
	if m != nil {
		return m.Events
	}
	return nil
}

type CreateEventRequest struct {
	CalendarID           string     `protobuf:"bytes,1,opt,name=calendarID,proto3" json:"calendarID,omitempty"`
	Event                *EventData `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateEventRequest) Reset()         { *m = CreateEventRequest{} }
func (m *CreateEventRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEventRequest) ProtoMessage()    {}
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{4}
}

func (m *CreateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRequest.Unmarshal(m, b)
}
func (m *CreateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRequest.Marshal(b, m, deterministic)
}
func (m *CreateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRequest.Merge(m, src)
}
func (m *CreateEventRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEventRequest.Size(m)
}
func (m *CreateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRequest proto.InternalMessageInfo

func (m *CreateEventRequest) GetCalendarID() string {
	if m != nil {
		return m.CalendarID
	}
	return ""
}

func (m *CreateEventRequest) GetEvent() *EventData {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventResponse struct {
	EventID              string   `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventResponse) Reset()         { *m = CreateEventResponse{} }
func (m *CreateEventResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEventResponse) ProtoMessage()    {}
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{5}
}

func (m *CreateEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventResponse.Unmarshal(m, b)
}
func (m *CreateEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventResponse.Marshal(b, m, deterministic)
}
func (m *CreateEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventResponse.Merge(m, src)
}
func (m *CreateEventResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEventResponse.Size(m)
}
func (m *CreateEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventResponse proto.InternalMessageInfo

func (m *CreateEventResponse) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

type UpdateEventRequest struct {
	CalendarID           string     `protobuf:"bytes,1,opt,name=calendarID,proto3" json:"calendarID,omitempty"`
	Event                *EventData `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateEventRequest) Reset()         { *m = UpdateEventRequest{} }
func (m *UpdateEventRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEventRequest) ProtoMessage()    {}
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{6}
}

func (m *UpdateEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventRequest.Unmarshal(m, b)
}
func (m *UpdateEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventRequest.Merge(m, src)
}
func (m *UpdateEventRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEventRequest.Size(m)
}
func (m *UpdateEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventRequest proto.InternalMessageInfo

func (m *UpdateEventRequest) GetCalendarID() string {
	if m != nil {
		return m.CalendarID
	}
	return ""
}

func (m *UpdateEventRequest) GetEvent() *EventData {
	if m != nil {
		return m.Event
	}
	return nil
}

type DeleteEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CalendarID           string   `protobuf:"bytes,2,opt,name=calendarID,proto3" json:"calendarID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventRequest) Reset()         { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()    {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{7}
}

func (m *DeleteEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequest.Unmarshal(m, b)
}
func (m *DeleteEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequest.Merge(m, src)
}
func (m *DeleteEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequest.Size(m)
}
func (m *DeleteEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequest proto.InternalMessageInfo

func (m *DeleteEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteEventRequest) GetCalendarID() string {
	if m != nil {
		return m.CalendarID
	}
	return ""
}

type CreateCalendarRequest struct {
	TeacherID            int32    `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCalendarRequest) Reset()         { *m = CreateCalendarRequest{} }
func (m *CreateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarRequest) ProtoMessage()    {}
func (*CreateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdb2b1a167884712, []int{8}
}

func (m *CreateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarRequest.Unmarshal(m, b)
}
func (m *CreateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *CreateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarRequest.Merge(m, src)
}
func (m *CreateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarRequest.Size(m)
}
func (m *CreateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarRequest proto.InternalMessageInfo

func (m *CreateCalendarRequest) GetTeacherID() int32 {
	if m != nil {
		return m.TeacherID
	}
	return 0
}

func init() {
	proto.RegisterType((*Nothing)(nil), "calendar.Nothing")
	proto.RegisterType((*EventData)(nil), "calendar.EventData")
	proto.RegisterType((*GetEventsRequestCalendar)(nil), "calendar.GetEventsRequestCalendar")
	proto.RegisterType((*GetEventsResponse)(nil), "calendar.GetEventsResponse")
	proto.RegisterType((*CreateEventRequest)(nil), "calendar.CreateEventRequest")
	proto.RegisterType((*CreateEventResponse)(nil), "calendar.CreateEventResponse")
	proto.RegisterType((*UpdateEventRequest)(nil), "calendar.UpdateEventRequest")
	proto.RegisterType((*DeleteEventRequest)(nil), "calendar.DeleteEventRequest")
	proto.RegisterType((*CreateCalendarRequest)(nil), "calendar.CreateCalendarRequest")
}

func init() {
	proto.RegisterFile("delivery/grpc/calendar/proto/calendar.proto", fileDescriptor_cdb2b1a167884712)
}

var fileDescriptor_cdb2b1a167884712 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x25, 0x79, 0xa6, 0xcf, 0xdc, 0xc8, 0x83, 0x37, 0x4f, 0x61, 0xa8, 0x55, 0xc3, 0xac, 0x2a,
	0x85, 0x06, 0x2a, 0x82, 0x2b, 0x11, 0x1b, 0x91, 0xba, 0x70, 0x11, 0x74, 0xe3, 0x46, 0xc6, 0xe4,
	0xd2, 0x06, 0x42, 0x12, 0x67, 0xc6, 0x82, 0x1f, 0xe4, 0x5f, 0xba, 0x90, 0x4c, 0x67, 0x92, 0x69,
	0xda, 0xba, 0x7b, 0xcb, 0x7b, 0xcf, 0x9c, 0x7b, 0xee, 0x9c, 0x93, 0x0c, 0x2c, 0x0a, 0xac, 0xca,
	0x3d, 0x8a, 0xdf, 0xc9, 0x56, 0xb4, 0x79, 0x92, 0xf3, 0x0a, 0xeb, 0x82, 0x8b, 0xa4, 0x15, 0x8d,
	0x6a, 0xfa, 0x72, 0xa9, 0x4b, 0xf2, 0xd0, 0xd6, 0x2c, 0x84, 0xeb, 0xcf, 0x8d, 0xda, 0x95, 0xf5,
	0x96, 0xfd, 0xf1, 0x20, 0xfc, 0xb0, 0xc7, 0x5a, 0xa5, 0x5c, 0x71, 0x72, 0x03, 0x7e, 0x59, 0x50,
	0x2f, 0xf6, 0xe6, 0x61, 0xe6, 0x97, 0x05, 0x79, 0x0c, 0x81, 0x2a, 0x55, 0x85, 0xd4, 0xd7, 0xad,
	0x43, 0x41, 0x62, 0x88, 0x0a, 0x94, 0xb9, 0x28, 0x5b, 0x55, 0x36, 0x35, 0xbd, 0xd2, 0x98, 0xdb,
	0x22, 0x33, 0x08, 0xa5, 0xe2, 0xa2, 0x1b, 0x8a, 0xf4, 0x81, 0xc6, 0x87, 0x06, 0xa1, 0x70, 0x8d,
	0x75, 0xa1, 0xb1, 0x40, 0x63, 0xb6, 0xec, 0x90, 0xbc, 0xe2, 0x52, 0x6e, 0x52, 0x3a, 0x89, 0xbd,
	0x79, 0x90, 0xd9, 0x92, 0xbd, 0x01, 0xfa, 0x11, 0x95, 0xde, 0x54, 0x66, 0xf8, 0xf3, 0x17, 0x4a,
	0xb5, 0x36, 0xd7, 0xe9, 0xd4, 0x14, 0xf2, 0x7c, 0x87, 0x62, 0x93, 0xea, 0xe5, 0x83, 0x6c, 0x68,
	0xb0, 0x77, 0x70, 0xeb, 0x30, 0x65, 0xdb, 0xd4, 0x12, 0xc9, 0x02, 0x26, 0xa8, 0x3b, 0xd4, 0x8b,
	0xaf, 0xe6, 0xd1, 0xea, 0x6e, 0xd9, 0x9b, 0xd5, 0xbb, 0x91, 0x99, 0x23, 0xec, 0x3b, 0x90, 0xb5,
	0x40, 0xae, 0x50, 0x43, 0x46, 0x9d, 0x3c, 0x07, 0xb0, 0x1c, 0x23, 0x1b, 0x66, 0x4e, 0x87, 0xbc,
	0x84, 0x40, 0xf3, 0xb5, 0x77, 0x17, 0x14, 0x0e, 0x27, 0x58, 0x02, 0x77, 0x47, 0x02, 0x66, 0xc9,
	0xce, 0xa7, 0xae, 0xd1, 0x8f, 0xb7, 0x65, 0xb7, 0xd1, 0xd7, 0xb6, 0xb8, 0xc7, 0x8d, 0x52, 0x20,
	0x29, 0x56, 0x38, 0x12, 0x18, 0x7f, 0x1e, 0xc7, 0x82, 0xfe, 0x58, 0x90, 0xbd, 0x86, 0x27, 0x87,
	0x7b, 0xd9, 0xa8, 0xec, 0xa0, 0xff, 0x26, 0xb6, 0xfa, 0xeb, 0x03, 0xb1, 0x8c, 0x75, 0x53, 0x2b,
	0xd1, 0x54, 0x15, 0x0a, 0xf2, 0xc5, 0x09, 0xb2, 0xcf, 0x9e, 0x0d, 0x97, 0xb8, 0xf4, 0x7d, 0x4c,
	0x9f, 0x9e, 0x3d, 0x63, 0x4c, 0xfe, 0x04, 0x91, 0xe3, 0x3d, 0x99, 0x0d, 0x67, 0x4f, 0x33, 0x9f,
	0x3e, 0xbb, 0x80, 0x9a, 0x59, 0x6f, 0x21, 0x72, 0x62, 0x71, 0x67, 0x9d, 0xa6, 0x35, 0xbd, 0x1d,
	0x50, 0xf3, 0x33, 0x76, 0x7c, 0xc7, 0x75, 0x97, 0x7f, 0x1a, 0xc6, 0x39, 0x7e, 0x0a, 0x37, 0xc7,
	0x7e, 0x93, 0x17, 0xe3, 0x85, 0x47, 0x49, 0x9c, 0x99, 0xf2, 0xfe, 0xd1, 0x37, 0x58, 0xf6, 0x6f,
	0xc7, 0x8f, 0x89, 0x7e, 0x3c, 0x5e, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x1a, 0xbf, 0x31,
	0x6b, 0x04, 0x00, 0x00,
}
