// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller/chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c50c23f77f30cc6, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type BroadcastMessage struct {
	ClassID              int32    `protobuf:"varint,1,opt,name=classID,proto3" json:"classID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AttachmentURLs       []string `protobuf:"bytes,4,rep,name=attachmentURLs,proto3" json:"attachmentURLs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessage) Reset()         { *m = BroadcastMessage{} }
func (m *BroadcastMessage) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessage) ProtoMessage()    {}
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c50c23f77f30cc6, []int{1}
}

func (m *BroadcastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessage.Unmarshal(m, b)
}
func (m *BroadcastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessage.Marshal(b, m, deterministic)
}
func (m *BroadcastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessage.Merge(m, src)
}
func (m *BroadcastMessage) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessage.Size(m)
}
func (m *BroadcastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessage proto.InternalMessageInfo

func (m *BroadcastMessage) GetClassID() int32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

func (m *BroadcastMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BroadcastMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BroadcastMessage) GetAttachmentURLs() []string {
	if m != nil {
		return m.AttachmentURLs
	}
	return nil
}

func init() {
	proto.RegisterType((*Nothing)(nil), "chat.Nothing")
	proto.RegisterType((*BroadcastMessage)(nil), "chat.BroadcastMessage")
}

func init() {
	proto.RegisterFile("controller/chat.proto", fileDescriptor_0c50c23f77f30cc6)
}

var fileDescriptor_0c50c23f77f30cc6 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0x47, 0x59, 0xef, 0xcf, 0xba, 0xe3, 0x1f, 0x24, 0xa8, 0x04, 0xab, 0x70, 0x85, 0x6c, 0xb5,
	0x82, 0x62, 0x2f, 0xab, 0x8d, 0xa0, 0x16, 0x01, 0x1b, 0xbb, 0x31, 0x17, 0x36, 0x81, 0x98, 0x39,
	0x32, 0xf3, 0x31, 0xfc, 0xd0, 0x62, 0x4e, 0x51, 0xae, 0x9b, 0xdf, 0x9b, 0xe6, 0x3d, 0x38, 0x73,
	0x94, 0xa5, 0x50, 0x4a, 0xbe, 0x5c, 0xb9, 0x80, 0x32, 0x6c, 0x0a, 0x09, 0xa9, 0xf9, 0xf7, 0xbd,
	0xea, 0xa0, 0x7d, 0x21, 0x09, 0x31, 0x4f, 0xab, 0xcf, 0x06, 0x4e, 0xc6, 0x42, 0xb8, 0x76, 0xc8,
	0xf2, 0xec, 0x99, 0x71, 0xf2, 0x4a, 0x43, 0xeb, 0x12, 0x32, 0x3f, 0x3e, 0xe8, 0xc6, 0x34, 0xfd,
	0xc2, 0xfe, 0x4e, 0x75, 0x0a, 0x0b, 0x89, 0x92, 0xbc, 0xde, 0x33, 0x4d, 0xdf, 0xd9, 0xed, 0x50,
	0x06, 0x0e, 0xd6, 0x9e, 0x5d, 0x89, 0x1b, 0x89, 0x94, 0xf5, 0xac, 0xfe, 0xfe, 0x23, 0x75, 0x09,
	0xc7, 0x28, 0x82, 0x2e, 0x7c, 0xf8, 0x2c, 0xaf, 0xf6, 0x89, 0xf5, 0xdc, 0xcc, 0xfa, 0xce, 0xee,
	0xd0, 0xeb, 0x3b, 0x68, 0x47, 0x92, 0xfb, 0x80, 0xa2, 0x6e, 0xe1, 0xf0, 0x4f, 0x8c, 0x27, 0x75,
	0x3e, 0xd4, 0x8e, 0x5d, 0xd9, 0x8b, 0xa3, 0x2d, 0xff, 0x09, 0x1a, 0xf7, 0xdf, 0x96, 0x43, 0x2d,
	0x7e, 0x5f, 0xd6, 0xe4, 0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xf8, 0xe9, 0x26, 0x0b,
	0x01, 0x00, 0x00,
}
