// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller/ctrl.proto

package ctrl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	ChatID               int32    `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	AttachmentURLs       []string `protobuf:"bytes,3,rep,name=attachmentURLs,proto3" json:"attachmentURLs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetChatID() int32 {
	if m != nil {
		return m.ChatID
	}
	return 0
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetAttachmentURLs() []string {
	if m != nil {
		return m.AttachmentURLs
	}
	return nil
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{1}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type BroadcastMessage struct {
	ClassID              int32    `protobuf:"varint,1,opt,name=classID,proto3" json:"classID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AttachmentURLs       []string `protobuf:"bytes,4,rep,name=attachmentURLs,proto3" json:"attachmentURLs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessage) Reset()         { *m = BroadcastMessage{} }
func (m *BroadcastMessage) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessage) ProtoMessage()    {}
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{2}
}

func (m *BroadcastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessage.Unmarshal(m, b)
}
func (m *BroadcastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessage.Marshal(b, m, deterministic)
}
func (m *BroadcastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessage.Merge(m, src)
}
func (m *BroadcastMessage) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessage.Size(m)
}
func (m *BroadcastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessage proto.InternalMessageInfo

func (m *BroadcastMessage) GetClassID() int32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

func (m *BroadcastMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BroadcastMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BroadcastMessage) GetAttachmentURLs() []string {
	if m != nil {
		return m.AttachmentURLs
	}
	return nil
}

type EventData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartDate            string   `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	ClassID              int32    `protobuf:"varint,6,opt,name=classID,proto3" json:"classID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventData) Reset()         { *m = EventData{} }
func (m *EventData) String() string { return proto.CompactTextString(m) }
func (*EventData) ProtoMessage()    {}
func (*EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{3}
}

func (m *EventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventData.Unmarshal(m, b)
}
func (m *EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventData.Marshal(b, m, deterministic)
}
func (m *EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventData.Merge(m, src)
}
func (m *EventData) XXX_Size() int {
	return xxx_messageInfo_EventData.Size(m)
}
func (m *EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_EventData proto.InternalMessageInfo

func (m *EventData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EventData) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *EventData) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *EventData) GetClassID() int32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

type GetEventsRequestCalendar struct {
	TeacherID            int32    `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequestCalendar) Reset()         { *m = GetEventsRequestCalendar{} }
func (m *GetEventsRequestCalendar) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequestCalendar) ProtoMessage()    {}
func (*GetEventsRequestCalendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{4}
}

func (m *GetEventsRequestCalendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequestCalendar.Unmarshal(m, b)
}
func (m *GetEventsRequestCalendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequestCalendar.Marshal(b, m, deterministic)
}
func (m *GetEventsRequestCalendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequestCalendar.Merge(m, src)
}
func (m *GetEventsRequestCalendar) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequestCalendar.Size(m)
}
func (m *GetEventsRequestCalendar) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequestCalendar.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequestCalendar proto.InternalMessageInfo

func (m *GetEventsRequestCalendar) GetTeacherID() int32 {
	if m != nil {
		return m.TeacherID
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*EventData `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{5}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*EventData {
	if m != nil {
		return m.Events
	}
	return nil
}

type DeleteEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventRequest) Reset()         { *m = DeleteEventRequest{} }
func (m *DeleteEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRequest) ProtoMessage()    {}
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaac058b8657cefa, []int{6}
}

func (m *DeleteEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRequest.Unmarshal(m, b)
}
func (m *DeleteEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRequest.Merge(m, src)
}
func (m *DeleteEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRequest.Size(m)
}
func (m *DeleteEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRequest proto.InternalMessageInfo

func (m *DeleteEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "ctrl.Message")
	proto.RegisterType((*Nothing)(nil), "ctrl.Nothing")
	proto.RegisterType((*BroadcastMessage)(nil), "ctrl.BroadcastMessage")
	proto.RegisterType((*EventData)(nil), "ctrl.EventData")
	proto.RegisterType((*GetEventsRequestCalendar)(nil), "ctrl.GetEventsRequestCalendar")
	proto.RegisterType((*GetEventsResponse)(nil), "ctrl.GetEventsResponse")
	proto.RegisterType((*DeleteEventRequest)(nil), "ctrl.DeleteEventRequest")
}

func init() {
	proto.RegisterFile("controller/ctrl.proto", fileDescriptor_aaac058b8657cefa)
}

var fileDescriptor_aaac058b8657cefa = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0xfe, 0x49, 0xc9, 0x04, 0xca, 0x62, 0xc1, 0x62, 0xad, 0x10, 0x8a, 0x22, 0x04,
	0xbd, 0x6c, 0x41, 0x45, 0x20, 0x0e, 0x9c, 0xb6, 0x45, 0x08, 0x69, 0xd9, 0x43, 0xd0, 0x5e, 0x90,
	0x38, 0x18, 0x67, 0x68, 0x22, 0x05, 0xbb, 0xd8, 0x03, 0x82, 0x77, 0xe0, 0x35, 0x78, 0x47, 0x8e,
	0xa8, 0x8e, 0x93, 0x86, 0xb4, 0x48, 0x68, 0x6f, 0x99, 0xef, 0xf3, 0xe4, 0x1b, 0xff, 0x6c, 0xc3,
	0x1d, 0xa9, 0x15, 0x19, 0x5d, 0x55, 0x68, 0x1e, 0x4b, 0x32, 0xd5, 0x7c, 0x63, 0x34, 0x69, 0x36,
	0xda, 0x7e, 0xa7, 0x1f, 0x60, 0xf2, 0x16, 0xad, 0x15, 0x6b, 0x64, 0xc7, 0x10, 0xca, 0x42, 0xd0,
	0x9b, 0x15, 0x0f, 0x92, 0x60, 0x36, 0xce, 0x7c, 0xc5, 0x18, 0x8c, 0x08, 0xbf, 0x13, 0x1f, 0x24,
	0xc1, 0x2c, 0xca, 0xdc, 0x37, 0x7b, 0x08, 0x53, 0x41, 0x24, 0x64, 0xf1, 0x19, 0x15, 0x5d, 0x66,
	0xe7, 0x96, 0x0f, 0x93, 0xe1, 0x2c, 0xca, 0x7a, 0x6a, 0x1a, 0xc1, 0xe4, 0x42, 0x53, 0x51, 0xaa,
	0x75, 0xfa, 0x33, 0x80, 0xa3, 0x33, 0xa3, 0x45, 0x2e, 0x85, 0xa5, 0x26, 0x93, 0xc3, 0x44, 0x56,
	0xc2, 0xda, 0x36, 0xb4, 0x29, 0xd9, 0x6d, 0x18, 0x53, 0x49, 0x15, 0xfa, 0xd8, 0xba, 0x60, 0x09,
	0xc4, 0x39, 0x5a, 0x69, 0xca, 0x0d, 0x95, 0x5a, 0xf1, 0xa1, 0xf3, 0xba, 0xd2, 0x81, 0xc9, 0x46,
	0x07, 0x27, 0xfb, 0x15, 0x40, 0xf4, 0xea, 0x1b, 0x2a, 0x5a, 0x09, 0x12, 0x6c, 0x0a, 0x83, 0x32,
	0x77, 0x23, 0x44, 0xd9, 0xa0, 0xcc, 0xaf, 0x9c, 0x7e, 0x0f, 0x22, 0x4b, 0xc2, 0x6c, 0x7f, 0x8a,
	0x7c, 0xe4, 0xfc, 0x9d, 0xb0, 0xdd, 0x2d, 0xaa, 0xdc, 0x79, 0x63, 0xe7, 0x35, 0x65, 0x97, 0x43,
	0xf8, 0x17, 0x87, 0xf4, 0x05, 0xf0, 0xd7, 0x48, 0x6e, 0x52, 0x9b, 0xe1, 0x97, 0xaf, 0x68, 0x69,
	0x29, 0x2a, 0x54, 0xb9, 0x30, 0xdb, 0x34, 0x42, 0x21, 0x0b, 0x34, 0x2d, 0xbf, 0x9d, 0x90, 0xbe,
	0x84, 0x5b, 0x9d, 0x4e, 0xbb, 0xd1, 0xca, 0x22, 0x7b, 0x04, 0x21, 0x3a, 0x85, 0x07, 0xc9, 0x70,
	0x16, 0x2f, 0x6e, 0xce, 0xdd, 0x95, 0x68, 0x49, 0x64, 0xde, 0x4e, 0x1f, 0x00, 0x5b, 0x61, 0x85,
	0x84, 0xce, 0xf2, 0xc9, 0x7d, 0x4e, 0x8b, 0x1f, 0x30, 0x5d, 0x16, 0x82, 0x96, 0xed, 0x0d, 0x63,
	0xcf, 0xe0, 0xfa, 0xee, 0x94, 0xed, 0x9a, 0x1d, 0xd7, 0x01, 0xfd, 0x93, 0x3f, 0xb9, 0x51, 0xeb,
	0xfe, 0x76, 0xb0, 0x27, 0x70, 0xf4, 0x0e, 0x55, 0x7e, 0xa1, 0xa9, 0xfc, 0x54, 0x4a, 0xe1, 0x60,
	0xfa, 0x25, 0x87, 0x3b, 0x16, 0xbf, 0x03, 0x60, 0x0d, 0x89, 0x4e, 0xfe, 0x79, 0x67, 0xd7, 0x2d,
	0xa8, 0xfb, 0x75, 0xeb, 0xbf, 0x40, 0x9e, 0xdc, 0xdd, 0xf3, 0x3d, 0xae, 0x53, 0x88, 0x97, 0x06,
	0x85, 0xa7, 0xc0, 0xfa, 0xb4, 0xfa, 0xbb, 0x38, 0x85, 0xf8, 0x72, 0x93, 0xff, 0xf7, 0xf2, 0xe7,
	0x10, 0x77, 0x18, 0x33, 0x5e, 0xbb, 0xfb, 0xd8, 0x7b, 0x7d, 0x67, 0xd7, 0xde, 0x87, 0x73, 0xf7,
	0x94, 0x3f, 0x86, 0xee, 0x2d, 0x3f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x02, 0x4e, 0xde, 0xfa,
	0xe4, 0x03, 0x00, 0x00,
}
